### ISSUE TITLE
multiple change:playback events being gnerated?

### ISSUE THREAD

**Issue by jck** [twolfson/google-music-electron#12]
I'm not sure if the issue is with google-music-electron or google-music.js, but It appears as if multiple(3 in my case) events are being generated when I pause or unpause.

**Comment by twolfson** [comment]
This is due to us using a MutationObserver on Google Music's webpage. Occasionally, we see a paused state before the next playing state so we choose to be more liberal than conservative with our events. Is this causing any issues for you?

**Comment by jck** [comment]
Instead of #11, I decided to try implementing a simple Mpris based Last fm scrobbler. I could work around the issue by filtering duplicate events. But I think, some DEs which provide mpris based notifications might end up sending multiple notifications for each event.

**Comment by twolfson** [comment]
Ah right, the scrobbler. As a workaround for now, you can use `_.debounce`:

http://underscorejs.org/#debounce

However, you are right. We should probably solve this in a larger scale to prevent frustration for DE notifications. Ideas for now:
- Add debouncing to `google-music.js`
- Refine tuning on playback mutation observer

**Comment by twolfson** [comment]
I might be missing something but why are we listening to `change:playback` for a scrobbler? Wouldn't we want song info instead (i.e. `change:song`)?

**Comment by twolfson** [comment]
Alright, I looked into this and added a proper fix as well as removed inaccurate "pause" events. The patch has been released in `google-music-electron@1.18.0`.
