### ISSUE TITLE
How the media shorctus work? (Ubuntu 14.04)

### ISSUE THREAD

**Issue by MaikoID** [twolfson/google-music-electron#14]
Hi. I'm wondering how the media shortcuts works. Currently I've set the play/pause shortcut to Ctrl+Alt+c, at the system keyboard shortcuts, and it works for every music player that I've experimented. How it's the first time I'm using a web app I don't know if it should work as the other off-line players.

Anyone could explain me this ?

BR

**Comment by twolfson** [comment]
We are currently using Electron's `global-shortcut` bindings which work across all platforms:

https://github.com/twolfson/google-music-electron/blob/1.18.1/lib/shortcuts.js

https://github.com/atom/electron/blob/v0.31.0/docs/api/global-shortcut.md

Are you encountering any errors with our current setup?

**Comment by MaikoID** [comment]
Ok, but:
1) How can I install it?
2) How can I configure it?

Thx in advance.

**Comment by twolfson** [comment]
Installation instructions are in the README:

https://github.com/twolfson/google-music-electron/tree/1.18.1#getting-started

Currently, we do not allow for configuring those shortcuts. However, we also integrate with MPRIS. I have a feeling 1 of those 2 bindings will work with your existing setup.

**Comment by iwoloschin** [comment]
I'm not sure if this is the same issue, but it's related to media keys so I think it is?

I've got gme running on two machines, one OS X 10.10 laptop and a desktop running Funtoo Linux.  On OS X it runs pretty nicely, media keys work well with no extra work.  On Funtoo I cannot seem to get the media keys on my keyboard to work (they _do_ work via extensions in Chrome proper).  Any thoughts on what I might be doing wrong with the Linux setup?

I'm happy to try some troubleshooting/debugging/etc but I'm honestly not sure where to start, I'm not really familiar with Electron.

**Comment by twolfson** [comment]
I am on vacation for 2 weeks. I don't know any solution for this right now. I will reply in 2 weeks.

**Comment by iwoloschin** [comment]
Enjoy your vacation!

**Comment by twolfson** [comment]
Alright, back. I am going to guess there is a compatbility issue between Funtoo and Electron. Are you receiving any error messages in `stderr` about media keys?

**Comment by iwoloschin** [comment]
Hope you had a good vacation!

I'm getting the following when I open gme:

~# google-music-electron
[24612:0911/083148:ERROR:browser_main_loop.cc(171)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
2015-09-11T12:31:48.811Z - info: Logger initialized. Writing info/warnings/errors to stdout. Writing all logs to "/home/iwoloschin/.config/google-music-electron/verbose.log"
2015-09-11T12:31:48.959Z - info: App ready. Opening Google Music window height=920, preload=/usr/lib64/node_modules/google-music-electron/lib/browser.js, skip-taskbar=undefined, use-content-size=true, width=1024, http_parser=2.3.0, node=1.6.3, v8=4.2.77.15, uv=1.4.2, zlib=1.2.8, ares=1.10.0-DEV, modules=43, openssl=1.0.1m, electron=0.26.1, atom-shell=0.26.1, chrome=42.0.2311.107, version=1.18.1
2015-09-11T12:31:49.058Z - warn: Failed to bind `mediaplaypause` shortcut
2015-09-11T12:31:49.062Z - warn: Failed to bind `medianexttrack` shortcut
2015-09-11T12:31:49.063Z - warn: Failed to bind `mediaprevioustrack` shortcut

Pressing the media keys (Fn+F4/F5/F6) on my keyboard doesn't seem to do anything.  Uncertain on what a good next step would be, my coding skills are mostly embedded C & Python, but if you give me some things to try happy to give it a shot!

**Comment by iwoloschin** [comment]
Gah.  I'm an idiot.

Chrome already had the media keys bound globally.  Disabled that (Extensions --> Keyboard Shortcuts) and restarted GME and everything is working fine.

_sigh_

**Comment by twolfson** [comment]
Yey, glad to hear it all worked out =)

**Comment by twolfson** [comment]
It's been 1 month since this ticket was initially opened with no clarification from @MaikoID. Closing this issue.
