### ISSUE TITLE
Bring window to the front by clicking the system tray icon when the window is not hidden

### ISSUE THREAD

**Issue by AngelEzquerra** [twolfson/google-music-electron#18]
It would nice if clicking on the system tray icon would bring the Google Music Electron window to the front, rather than minimizing it, when the window does not have the focus.

I am running Google Music Electron with the --skip-taskbar flag. This works great. However, if I do not click the tray icon to minimize the window, and instead I just bring some other window to the front, hiding the Google Music Electron window behind it, then bringing Google Music Electron back to the front is a two click process: First I must click on the tray icon to hide the window, and then I click on it again to show it. Instead it would be much nicer if I could just click on the window once to bring it to the front. clicking it again (now that it is on the foreground) would hide it.

**Comment by twolfson** [comment]
This is a personal preference. I use `--hide-via-tray` so when the window is already out of focus, this allows me to clean up my taskbar without needing to click twice to focus the window.

**Comment by AngelEzquerra** [comment]
But that does not let me do what I want. What I want is to _show_ the window when it is not being shown, in a single click. Currently you cannot do that. I'd basically like the system tray icon behave as a regular taskbar icon (which always brings the window to the front first, and only minimizes it when the window is on the foreground).

**Comment by twolfson** [comment]
Can you provide examples of the tray icons where you experienced that behavior? I am pretty sure I am reproducing Amarok's behavior.

**Comment by AngelEzquerra** [comment]
There are several examples. Not all of them behave in exactly the way I
described, but all of them make sure that you never need to click twice to
show the window:
- All of Microsoft´s tray widgets, such as the clock, the volume bar, the
  wifi indicator and the batery indicator, will show the widget with one
  click, and hide it with another. The only difference compared with the
  behavior I suggested is that those widgets are automatically hidden when
  they lose the focus. The same behavior can be found on Google Drive and
  Dropbox.
- Cisco Jabber (a messaging tool) and I believe always brings its window to
  the forefront when clicked. The difference with my suggestion is that
  clicking the jabber tray icon when the window is at the front does not hide
  it.

I think that what I proposed makes the most sense, but if that is not OK I
would at least go for the behavior of the microsoft widgets. Having to
click twice on a tray icon to show the window is very annoying and
surprising IMHO.

**Comment by twolfson** [comment]
Eh, not being able to show a specific makes me doubt this is a common design pattern =/

With respect to the examples you gave:
- Tray widgets are not correlative to this design because they inherently live in the tray whereas this is a shortcut for accessing/controlling our application
- Cisco Jabber isn't doing anything with respect to hiding to tray which doesn't correspond to our behavior

As mentioned before, I am replicating Amarok's behavior when it has "Hide to tray" enabled =/

I suggest for your use case, try using `Alt+Tab` or clicking on the icon in the taskbar (not tray). Still considering this a won't fix for now.

**Comment by AngelEzquerra** [comment]
I think the reason that I cannot find better examples is that there are not
that many programs that hide to the system tray in the first place.

In any case, my problem is that I have configured the program to not have a
taskbar icon. Thus the only way that I have to show the program without
using the keyboard is by clicking on the tray icon. The problem is that
currently that may require one or two clicks on the tray icon, and you
cannot tell for sure in advance!

I personally would be OK with Google Music Electron behaving exactly as
Cisco Jabber does. That is, clicking on the system tray would _always_
bring the program to the front, and would never minimize it. To minimize it
you would need to click on the minimize button on the main window. Would
that be reasonable?

**Comment by twolfson** [comment]
I might have missed something but I thought you were using `--hide-to-tray` not `--skip-taskbar` as the CLI flags. What's your current configuration setup?

**Comment by AngelEzquerra** [comment]
Hi,

I am using the "skip taskbar" option, which I configured through the new
options dialog. That is why I cannot just use the taskbar icon to minimize
or restore the main window.

**Comment by twolfson** [comment]
Alright, going to do some user testing. I have create a branch that has `focus` as part of the window toggling behavior. Going to use it for a few days and see how I feel.

**Comment by twolfson** [comment]
The branch is `/dev/explore.focus` if you are curious.

https://github.com/twolfson/google-music-electron/tree/dev/explore.focus
