### ISSUE TITLE
Windows 10: Instant crash when playing certain tracks

### ISSUE THREAD

**Issue by jacobped** [twolfson/google-music-electron#24]
First off, I've tested and verified that the following bug happens for me on two separate computers. 

**The Problem**
When I play certain music tracks the application will instantly crash.
The same tracks play perfectly fine using Google Chrome and have done so previously using an older version of the application, before I updated it to the newest release today. 
I haven't updated the application for at least a few weeks and have no idea what the previous version was, where it didn't instantly crash when playing these tracks.
And in case it matters, I have an All Access subscription with Google Play Music. 

**System**
Both computers is running Windows 10 x64 Pro. And both were a fresh win10 install back when I set them up.

**Version list from the above tab:**
Version: 2.2.1
Electron version: 0.34.2
Node.js version: 4.1.1
Chromium version: 45.0.2454.85

**Tendency**
So far I've concluded that it seems to be a tendency with tracks including the following characters in their name: 

```
"()
```

But It won't always crash when playing tracks using those characters.
An example is Pharrell William's:

```
Happy (From "Despicable Me 2")
```

Which plays just fine.

But Ellie Goulding's:

```
Love Me Like You Do (From "Fifty Shades of Grey")
```

Will make the application crash instantly when you try to play it.

**A Playlist**
I've made a public playlist with some of the tracks that I've found to make the application crash instantly when you try to play them: [Crash playlist](https://play.google.com/music/playlist/AMaBXykp9fFANZR7zbdP5ymzac6v04aBJ1i3vHXQ4mDdI2kT_2Kb5e53NzarEuCgAQ7N5Cu4wjW0MdZ0HtiZDyJs1IjsafZWOg==)

And last but not least. 
**The log.** 
I've played 3 of the tracks on the playlist, that makes the application crash and one which didn't. I've also separated the text for each start of the application in the log. To make it easier to read.
You can find it here on pastebin: http://pastebin.com/p81AkvtY

**Comment by twolfson** [comment]
Wow, thanks for the detailed report. Going to look into reproducing the error now.

It looks like Linux Mint 17.1 has no issues with the playlist.

**Comment by twolfson** [comment]
I have successfully gotten a crash on Windows 7 (via `ievms`). It's really strange that there's no crash dump or anything -- makes me feel like this is Flash doing something o_o

**Comment by twolfson** [comment]
Ah, it seems to be something related to `google-music.js`. I disabled the code that initializes/watches and I no longer get a crash.

**Comment by twolfson** [comment]
Still underway with triage -- we have tracked down the source of the issue to `change:song`. It looks like `ipc` doesn't like JSON objects with quotes and parentheses but we are trying to create a minimal test case.

**Comment by twolfson** [comment]
I believe we have a potential workaround (e.g. using `JSON.stringify/parse`) but want to verify the case first.

**Comment by twolfson** [comment]
Alright, good thing I kept on triaging. The issue is we are using too long of a tooltip on Windows. For example, this code inside of `app-tray.js` will make it crash:

``` js
setTimeout(function () {
      tray.setToolTip(
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n' + 
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n' + 
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n' + 
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n' + 
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n' + 
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n'
      );
}, 1000);
```

I think the workaround for us will be to truncate any long titles/artists/albums with ellipses. I'm going to see if there are any issues on Electron about this (and maybe report one about updating the docs to say Windows has a max length).

**Comment by twolfson** [comment]
For the record, the Windows limit is 127.

``` js
setTimeout(function () {
    var str = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n' + 
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n' + 
    'aaaaaaaaaaaaaaaaaaa\n' + 
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n';
    console.log(str.length);

    tray.setToolTip(str);
}, 1000);
```

**Comment by twolfson** [comment]
Alright, opened an issue on `electron`. Going to implement a workaround with truncation for now.

**Comment by jacobped** [comment]
I'm impressed with how quickly you found the problem and a solution. Good job. And thanks!

**Comment by twolfson** [comment]
Alright, the patch is live in `2.3.0`. To upgrade, follow the instructions below. Thanks again for the detailed report and sample playlist :+1: 

``` bash
# Install latest version of `google-music-electron`
npm install -g google-music-electron@latest
```

**Comment by jacobped** [comment]
Yep, now it works perfectly yet again. Thanks!
