### ISSUE TITLE
Window size/state is not preserved between sessions

### ISSUE THREAD

**Issue by Keavon** [twolfson/google-music-electron#32]
When I resize or maximize the window, next time I open the application it is the default small size again. Please make it preserve the size and state (maximized or not) between sessions.

**Comment by twolfson** [comment]
I am open to supporting this, we could probably preserve the variables in our config. Would you be interested in opening a PR for this?

**Comment by Keavon** [comment]
Sure, I could give that a try, but I'm not as familiar as you probably are with Electron. If you can't, I could probably add it in the next few days.

**Comment by twolfson** [comment]
Yep, I have plenty of other tasks on my queue. Please let me know if you need any help =)

**Comment by twolfson** [comment]
Forgot to close this but it was resolved in `2.10.0` via @JordanRobinson in #42
