### ISSUE TITLE
Taskbar and tray icons aren't the official logo and are black-on-black

### ISSUE THREAD

**Issue by Keavon** [twolfson/google-music-electron#33]
It's almost impossible to see the icons on Windows 10 because the task bar is black and so is the icon. Also, the current icon is not the official Google Play Music logo. To fix this, it should be replaced with the official orange logo.

**Comment by Keavon** [comment]
I am currently working on a PR for this.

**Comment by twolfson** [comment]
We already have a PR in progress for altering the tray icons (#28). However, we are avoiding anything official as we aren't affiliated with Google or Google Music.
