### ISSUE TITLE
Integrate Play Midnight for Google Play Music

### ISSUE THREAD

**Issue by Keavon** [twolfson/google-music-electron#34]
[Play Midnight for Google Play Music](https://chrome.google.com/webstore/detail/play-midnight-for-google/ljmjmhjkcgfmfdhgplikncgndbdeckci?utm_source=chrome-app-launcher-info-dialog) is a Chrome extension that modifies the UI to heavily improve aesthetics and user experience of Google Play Music. It would be wonderful if it could be somehow integrated, although I don't know how exactly a Chrome extension could be integrated with an Electron app.

**Comment by twolfson** [comment]
We are trying to keep this app minimally focused and have chosen to not support theming. Here are alternative apps which support theming:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

https://github.com/radiant-player/radiant-player-mac
