### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by arboleya** [twolfson/google-music-electron#4]
When I start up the app, I get an error regarding the menu initialization:

> Could not find function for menu command "undefined" under label "undefined"

It fails and thus the tray icon and mediakeys doesn't work as well.

![startup-error](https://cloud.githubusercontent.com/assets/26660/7710367/d17d0aba-fe39-11e4-8d65-e7d55585a079.png)

**Comment by arboleya** [comment]
Ok, there's no **`command`** property in [lib/menus/darwin.json:7~9](https://github.com/twolfson/google-music-electron/blob/master/lib/menus/darwin.json#L7-L9), causing the if/else conditions to fail at [lib/app-menu.js:38~41](https://github.com/twolfson/google-music-electron/blob/master/lib/app-menu.js#L38-L41)

**Comment by twolfson** [comment]
Ah, that would do it. I was naive and didn't cross check the different menus. We will need to add another `if` check for `type === separator` when `command === undefined`.

**Comment by arboleya** [comment]
Simple enough, PR sent :beers:

**Comment by twolfson** [comment]
This was repaired via your PR, #5, and released in `1.10.0`. Thanks again!
