### ISSUE TITLE
Authentication after each start.

### ISSUE THREAD

**Issue by bbergler** [twolfson/google-music-electron#41]
I have to sign in after each start of the app.

I checked the cookies are stored in the `.config/google-music-electron/` directory but I still have to sign-in.

I tried the npm version and the master branch direct from github same result.

**Comment by twolfson** [comment]
I'm not sure exactly what would cause this. Are there any configurations for your Google account which have you reauthenticate more frequently?

**Comment by bbergler** [comment]
It worked after removing the configuration and reinstalling.
Thanks for creating this project.

**Comment by twolfson** [comment]
Cool, I'm glad to hear you got it working =)
