### ISSUE TITLE
Custom CSS style

### ISSUE THREAD

**Issue by skylize** [twolfson/google-music-electron#47]
I'm a dark-theme junky, and would love to be able to customize away Google's stark-white background. Is there somewhere in the folder structure I could drop a stylesheet that would get picked up automatically? If not, would you consider adding support for custom styles? Thx

**Comment by twolfson** [comment]
We prefer to keep our library as simple as possible. I'd recommend checking out our full featured relative "Google Play Music Desktop Player":

https://www.googleplaymusicdesktopplayer.com/

If you're still interested in using our library instead, I'd be open to supporting this feature in some capacity

**Comment by skylize** [comment]
Thanks for the suggestion.

I don't think I really need all the bells and whistles. Seems a little lame to me that I need to get the "full featured" version with Voice Control, just to get some basic CSS support.

I would not expect applying a single stylesheet file to an existing DOM to add much complexity to the project.

But I guess if you see think of this repo as _just_ a library, I kind of see where you're coming from. I guess I'll give Desktop Player a whirl. Being able to minimize to the Tray is probably nice to have.

**Comment by twolfson** [comment]
Yea, I think the single stylesheet is trivial but I don't want to add it if you're going to go elsewhere ;) Let me know when you've decided =)
