### ISSUE TITLE
Hey, want to combine our efforts for the same Google Play application?

### ISSUE THREAD

**Issue by coreybruce** [twolfson/google-music-electron#48]
hey there I have made my own Google Play Music application of my own in very good working condition and still being updated and I found your project and found it interesting, would you like to combine our efforts to create a better application.

I have been keep it up to date ect, you can find my project at https://gitlab.com/coreybruce/GooglePlayMusic

Hope to hear back from you :)

**Comment by twolfson** [comment]
I'm happy to accept contributions but not really looking to add too many new features. Keeping it simple leads to less things to maintain which is where I'm happier at now

There's a much more feature complete project here:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-
