### ISSUE TITLE
Back/Forward support

### ISSUE THREAD

**Issue by johnfraney** [twolfson/google-music-electron#6]
I might be missing something, but I can't seem to get keyboard or mouse back/forward browser history shortcuts to work (`g-m-e` version 1.12.0, Arch x64).

Everything else is working nicely. Great work!

**Comment by twolfson** [comment]
Nope, you aren't missing anything. I have been attempting to see if Electron would support this as a built-in or at least point us in the right direction for extracting from the Chromium source. However, it looks like we might be on our own:

https://github.com/atom/electron/issues/1862

**Comment by johnfraney** [comment]
Hmm. I see. I'd have to do some digging in the Electron source code, but it would be handy if we could inject some custom JS into the page, then bind our keyboard/mouse shortcuts to back/forward functions (e.g., `history.go(-1)`) in the same way I assume the media keys are handled.

**Comment by twolfson** [comment]
Electron supports injected JS via `preload`; that is how we handle our Google Music bindings:

https://github.com/twolfson/google-music-electron/blob/1.12.0/lib/google-music-electron.js#L166

I have been waffling whether we should go for a full address bar or something inline. In `google-music-webkit`, I had a full address bar and it felt very nice; especially for debugging.

https://github.com/twolfson/google-music-webkit/blob/2.0.0/docs/screenshot.png

`radiant-player-mac` places arrows next to the search box:

https://camo.githubusercontent.com/41769a520285d2e881761d0d94d320277271cf63/68747470733a2f2f7261772e6769746875622e636f6d2f6b62686f6d65732f72616469616e742d706c617965722d6d61632f67682d70616765732f696d616765732f6170706c69636174696f6e2e706e67

**Comment by twolfson** [comment]
I finally had free time and enough frustration with the lack of forward/back buttons that they are now implemented in `1.14.0` =)

**Comment by johnfraney** [comment]
Nice! I'll test it out today.
